---
name: postgres
director_uuid: 36d4ba35-bed3-4993-b31b-d570af0f961d
release:
  name: cf-postgres
  version: 0+dev.5 

compilation:
  workers: 2
  cloud_properties:
    ram: 8192
    disk: 8096
    cpu: 4
  network: default
  reuse_compilation_vms: true 

update:
  canaries: 1
  canary_watch_time: 3000 - 180000
  update_watch_time: 3000 - 180000
  max_in_flight: 2
  max_errors: 1

networks:
 - name: default
   subnets:
   - range: 10.68.45.0/24
     gateway: 10.68.45.1
     dns:
     - 10.103.42.51
     static:
     - 10.68.45.151
     - 10.68.45.152
     - 10.68.45.153
     reserved:
     - 10.68.45.2-10.68.45.150
     cloud_properties:
      name : PCF_SERVICES

resource_pools:
 - name: rp1
   network: default
   stemcell:
    name: bosh-vsphere-esxi-centos-go_agent
    version: 2776
   cloud_properties:
    ram: 16500
    disk: 4096
    cpu: 2
   env:
    bosh:
      password: $6$2f6qtRfO$oJOeKk/ZDNb7PWnvMiXDC/HstKiLiZCBHP32KHFVeM9rXgs4W/JJiI4a/eHoddhxJzorLYgi2JUQiOKxZko4M.
      # c1oudc0w - password generated using mkpasswd -m sha-512

jobs:
 - name: postgres-server
   template: postgres-server
   instances: 1
   resource_pool: rp1
   persistent_disk: 4096
   properties:
     host: 10.68.45.151
   networks:
   - name: default
     static_ips:
     - 10.68.45.151

properties:
     host: 10.68.40.201
